### ISSUE TITLE
Minor issue with: Page Sections Slide Toggle

### ISSUE THREAD

**Issue by kyliescott** [tomsWebConsulting/twcsl#5]
Hi there, 

Having trouble changing the data toggle color of the icon in the code you've provided:

**<x-twc-psst data-toggle-color="red"></x-twc-psst>

Despite inserting different colors into the code, the result is always red. Any idea what the issue may be here?

Thanks so much!

**Comment by tomsWebConsulting** [comment]
Did you use the **data-toggle-color** attribute as mentioned in the [read me](https://github.com/tomsWebConsulting/twcsl/tree/main/v7.1/Page%20Sections%20Slide%20Toggle)?

**Comment by kyliescott** [comment]
Yes. It remains red, despite me changing the color in the code.

**Comment by tomsWebConsulting** [comment]
Please [post the URL for a page](https://support.squarespace.com/hc/en-us/articles/219311968-Sharing-URLs-from-your-site) on your site where I can see your issue.

A link to the backend of the your site won’t work, i.e. a url that contains /config/.

Please set up a [site-wide password](https://support.squarespace.com/hc/en-us/articles/205815528-Site-wide-passwords), if your site is not public and you've not already done so.

Post the password here.

Adding a site-wide password does not allow anyone to alter your site. It only allows those with the password to see your site.

Please read the [site-wide password](https://support.squarespace.com/hc/en-us/articles/205815528-Site-wide-passwords) and [how to share a link](https://support.squarespace.com/hc/en-us/articles/219311968-Sharing-URLs-from-your-site) documentation to understand how they work.

I can then take a look at your issue.

**Comment by kyliescott** [comment]
https://www.aboutfilms.tv/films

password: masterminds

**Comment by tomsWebConsulting** [comment]
Thank you for discovering a bug in the code. I have fixed the issue.

![Screen Shot 2023-04-12 at 5 38 38 PM](https://user-images.githubusercontent.com/76893606/231618012-3aa3eb5e-de05-412b-8882-0b65bb6c47a2.png)

Please reinstall the code. Also be sure to set the duration value in the code. The previous value was hard coded at 10.

Let me know how it goes.

**Comment by kyliescott** [comment]
Voila! Thank you so much!
