### ISSUE TITLE
Prepend Breadcrumb to Store Page Breadcrumbs

### ISSUE THREAD

**Issue by frankbracq** [tomsWebConsulting/twcsl#9]
Hi Tom

I'm trying to implement "Prepend Breadcrumb to Store Page Breadcrumbs" on this page genealog.ie/boutique. I've entered "accueil" as the urlSlug in the script. But it doesn't work. Did I mis something or is this a bug?
Thanks in advance for your help
![screenshot2](https://github.com/tomsWebConsulting/twcsl/assets/35921662/1a8b8691-4ee8-43b1-9951-f623cb00a037)
![screenshot3](https://github.com/tomsWebConsulting/twcsl/assets/35921662/5d8a19ee-90cd-4b0a-861e-3415394be1b7)

**Comment by tomsWebConsulting** [comment]
This is not a bug but you have some custom code that is overwriting what my code does, remove it.

$(document).ready(function() {
	$('a.ProductItem-nav-breadcrumb-link').attr('href','/boutique');
});

**Comment by tomsWebConsulting** [comment]
This is not a bug but you have some custom code that is overwriting what my code does, remove it.

$(document).ready(function() {
	$('a.ProductItem-nav-breadcrumb-link').attr('href','/boutique');
});
